# Tag options for internal Sage teams
template:
  path: "sc-tag-options.j2"
stack_name: "sc-tag-options"
stack_tags:
  OwnerEmail: "it@sagebase.org"
dependencies:
  - "prod/sc-portfolio-ec2.yaml"
  - "prod/sc-portfolio-ec2-external.yaml"
  - "prod/sc-portfolio-s3-basic.yaml"
  - "prod/sc-portfolio-scheduled-jobs.yaml"
sceptre_user_data:
  CostCenters: !file https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/v0.6.9/templates/tags/SageFinancialProgramCodes.json
  ProductIDs:
    - !stack_output_external sc-portfolio-ec2::SCEC2portfolioId
    - !stack_output_external sc-portfolio-s3-basic::SCS3portfolioId
    - !stack_output_external sc-portfolio-scheduled-jobs::SCScheduledJobsPortfolioId
